// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

const (
	CognitoScopes = "cognito.Scopes"
)

// InfoResponseContent defines model for InfoResponseContent.
type InfoResponseContent struct {
	AuthenticationFlowType *string `json:"authenticationFlowType,omitempty"`
	Region                 *string `json:"region,omitempty"`
	UserPoolId             *string `json:"userPoolId,omitempty"`
	UserPoolWebClientId    *string `json:"userPoolWebClientId,omitempty"`
}

// InternalServerErrorResponseContent defines model for InternalServerErrorResponseContent.
type InternalServerErrorResponseContent struct {
	ErrorMessage string `json:"errorMessage"`
}

// InvalidInputErrorResponseContent defines model for InvalidInputErrorResponseContent.
type InvalidInputErrorResponseContent struct {
	ErrorMessage string `json:"errorMessage"`
}

// SayHelloResponseContent defines model for SayHelloResponseContent.
type SayHelloResponseContent struct {
	Message string `json:"message"`
}

// SayHelloParams defines parameters for SayHello.
type SayHelloParams struct {
	Name string `form:"name" json:"name"`
}
